-- Setup a list of audio ID's and properties to use. (These values can be changed as needed)

-- To change the sound ID of a material, change the 'id' variable.
-- To change the volume, change the volume variable.
-- To change the playback speed of a sound, change the speed variable.

local IDList = {
	Air = {id = "rbxassetid://329997777", volume = 0, speed = 1.00},
	Asphalt = {id = "rbxassetid://277067660", volume = 0.60, speed = 1.00},
	Basalt = {id = "rbxassetid://3190903775", volume = 0.60, speed = 1.00},
	Brick = {id = "rbxassetid://178190837", volume = 0.60, speed = 1.00},
	Cobblestone = {id = "rbxassetid://178190837", volume = 0.60, speed = 1.00},
	Concrete = {id = "rbxassetid://277067660", volume = 0.60, speed = 1.00},
	CorrodedMetal = {id = "rbxassetid://177940974", volume = 0.60, speed = 1.00},
	CrackedLava = {id = "rbxassetid://3190903775", volume = 0.60, speed = 1.00},
	DiamondPlate = {id = "rbxassetid://177940974", volume = 0.60, speed = 1.00},
	Fabric = {id = "rbxassetid://9083849830", volume = 0.40, speed = 1.00},
	Foil = {id = "rbxassetid://178190837", volume = 0.60, speed = 1.00},
	Forcefield = {id = "rbxassetid://329997777", volume = 0.60, speed = 1.00},
	Glass = {id = "rbxassetid://178190837", volume = 0.60, speed = 1.00},
	Granite = {id = "rbxassetid://178054124", volume = 0.60, speed = 1.00},
	Grass = {id = "rbxassetid://9064714296", volume = 0.60, speed = 1.00},
	Glacier = {id = "rbxassetid://7047108275", volume = 0.40, speed = 1.00},
	Ground = {id = "rbxassetid://9064714296", volume = 0.60, speed = 1.00},
	Ice = {id = "rbxassetid://7047108275", volume = 0.40, speed = 1.00},
	Limestone = {id = "rbxassetid://9083846829", volume = 0.60, speed = 1.00},
	LeafyGrass = {id = "rbxassetid://3098847639", volume = 0.60, speed = 1.00},
	Marble = {id = "rbxassetid://178190837", volume = 0.60, speed = 1.00},
	Metal = {id = "rbxassetid://177940974", volume = 0.60, speed = 1.00},
	Mud = {id = "rbxassetid://6441160246", volume = 0.60, speed = 1.00},
	Neon = {id = "rbxassetid://177940974", volume = 0.60, speed = 1.00},
	Pebble = {id = "rbxassetid://178190837", volume = 0.60, speed = 1.00},
	Plastic = {id = "rbxassetid://4416041299", volume = 0.60, speed = 1.40},
	Pavement = {id = "rbxassetid://277067660", volume = 0.60, speed = 1.00},
	Rock = {id = "rbxassetid://178190837", volume = 0.60, speed = 1.00},
	Sand = {id = "rbxassetid://9083846829", volume = 0.40, speed = 1.00},
	Slate = {id = "rbxassetid://178054124", volume = 0.60, speed = 1.00},
	Snow = {id = "rbxassetid://8453425942", volume = 0.60, speed = 1.00},
	Salt = {id = "rbxassetid://9083846829", volume = 0.40, speed = 1.00},
	Sandstone = {id = "rbxassetid://3190903775", volume = 0.60, speed = 0.75},
	SmoothPlastic = {id = "rbxassetid://178190837", volume = 0.60, speed = 1.00},
	Wood = {id = "rbxassetid://3199270096", volume = 0.60, speed = 1.00},
	WoodPlanks = {id = "rbxassetid://211987063", volume = 0.60, speed = 1.00}
}

return IDList
